standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/configs/externalsecret.yaml
**Before**: SecretKey and Property took the same value. This is compatible for env variables where the `key` stored in secret backend equals the variable. For secrets like json files or keys that differs from variable value, it isn't compatible.
```
secrets:
- APPSETTINGS_JSON
```
```
piVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
.
.
spec:
data:
- remoteRef:
property: APPSETTINGS_JSON
secretKey: APPSETTINGS_JSON
.
.
```
Now
```
secrets:
- secretKey: appsettings.json
property: APPSETTINGS_JSON
- secretKey: AWS_ACCESS_KEY_ID
```
```
piVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
.
.
spec:
data:
- remoteRef:
property: APPSETTINGS_JSON
secretKey: appsettings.json
- remoteRef:
property: AWS_ACCESS_KEY_ID
secretKey: AWS_ACCESS_KEY_ID
.
.
```
=> Add secretKey and property to externalsecret values

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/configs/configmap.yaml
This PR is to adjust configMap creation for `deployment` `cronjobs` and `jobs` regarding script data. More Adjustments would be made to allow us to use script files from other repos to generate configMap data with the standard library.
Using our example in the PR:
```
apps:
nginx:
volumes:
- name: scripts
type:
configMap:
name: daily-sitemap-gen-script
defaultMode: 0777
configMapData:
run_daily_sitemap_gen.sh: |
#!/bin/bash
DATE=$(date +%d_%m)
```
configMap should look like this:
=> Adjust configMap template for script data

standard-app/templates/autoscaling/hpa.yaml
Default version for HPA is v2 starting from Kubernetes 1.27 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#:~:text=kubectl%20now%20uses%20HorizontalPodAutoscaler%20v2%20by%20default.%20(%23114886%2C%20%40a7i)
=> set hpa version to v2

standard-app/templates/configs/externalsecret.yaml
Lack of these parameters cause kube-prometheus-stack external secrets stay in Out-of-sync state all the time.
=> adding additional parameters

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/workloads/deployment.yaml
- adds a livenessProbe map to the deployment template to allow configuring liveness probes
- adds an example to the `example.values.yaml`
=> Add liveness probe to workloads

standard-app/templates/configs/externalsecret.yaml
This should fix this issue for GCP when using SecretManager.
```
Warning  UpdateFailed  8m47s (x18 over 19m)  external-secrets  error retrieving secret at .data[0], key: GX-TRIAL-UPLOADS_map[secretKey:JWT_SECRET_KEY], err: unable to access Secret from SecretManager Client: rpc error: code = InvalidArgument desc = The provided Secret ID [projects/epicore-dev/secrets/GX-TRIAL-UPLOADS_map[secretKey:JWT_SECRET_KEY]/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]
```
=> Fix format violation caused by concatenating map object and string

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/network/ingress.yaml
- allows list of ingresses,
- `.Values.ingress` is now Deprecated and will be dropped in a future release
=> replace extra ingresses with ingresses

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/network/service.yaml, standard-app/templates/workloads/deployment.yaml
**NOTE:** **BREAKING CHANGES**
Reconfigures the services and container templates:
- An app can have more than one service defined in a list at `apps.<id>.services`.
- remove services configuration using list of containers.
- An app can have more than one service targeting one container with one or more than one ports
- A container in an app can have more than one port defined in a list at `apps.<id>.containers.<id>.ports` matched with `apps.<id>.services`
- An app with just one container can have ports defined at the top level at `apps.<id>.ports` matched with `apps.<id>.services`
- Allows better naming of ports and services
=> Refactor services configuration per app & reconfigure container ports

standard-app/example.values.yaml, standard-app/templates/network/service.yaml
Allow services to have list of ports in `apps.<id>.services` so we can have something like
```yaml
apiVersion: v1
kind: Service
metadata:
name: example-app-2
labels:
app: example-app-2
product: standard-app
label1: somevalue
label2: anothervalue
spec:
type: ClusterIP
ports:
- name: web
port: 3003
protocol: TCP
targetPort: 3003
- name: metrics
port: 3006
protocol: TCP
targetPort: 3006
selector:
app: example-app-2
```
Building on https://github.com/cloudkite-io/helm-standard-library/pull/53
=> configure service values to have multiple ports

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/network/gateway-iap-backend.yaml, standard-app/templates/network/gateway.yaml, standard-app/templates/network/http-routes.yaml
This PR:
- Add Gateway API to the standard library
- Update example YAML
> PS: Aside from the IAP Backend Policy, the Gateway API should be the same for other cloud environment clusters when enabled.
=> Add GateWay API to library and update example file

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/configs/externalsecret.yaml
1. remove the need to specify `data` in `secrets` map
The following format is not supported anymore:
```
secrets:
data:
```
2. Move `dataFrom` block on the top of the conditional that checks if secrets are of a `map` kind
3. Merge `vault` and `aws` conditionals into one as they were about the same
=> remove data entry from the secrets

standard-app/templates/configs/_externalsecret.tpl
This PR:
- Uses `secret.property` as the secretKey in Kubernetes secret if there's a `property` in the secret declaration instead of `key` name. Before, when we have something like this:
```
secrets:
- secretKey: MONGO_CRED
property: mongo-username
- secretKey: MONGO_CRED
property: mongo-password
```
We get(same Kubernetes secret key name, could break external-secret):
```
- secretKey: MONGO_CRED
remoteRef:
key: HELM-STANDARD-LIBRARY_MONGO_CRED
property: mongo-username
- secretKey: MONGO_CRED
remoteRef:
key: HELM-STANDARD-LIBRARY_MONGO_CRED
property: mongo-password
```
Now with this change, with the same secret declaration, we get:
```
- secretKey: mongo-username
remoteRef:
key: HELM-STANDARD-LIBRARY_MONGO_CRED
property: mongo-username
- secretKey: mongo-password
remoteRef:
key: …
```
=> [rework-structure] branch-off work on external-secret

.github/workflows/standard-app-publish.yaml, standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/_labels.tpl, standard-app/templates/autoscaling/hpa.yaml, standard-app/templates/autoscaling/mpa.yaml, standard-app/templates/autoscaling/vpa.yaml, standard-app/templates/configs/_configmap.tpl, standard-app/templates/configs/_externalsecret.tpl, standard-app/templates/configs/configmap.yaml, standard-app/templates/configs/externalsecret.yaml, standard-app/templates/network/ingress.yaml, standard-app/templates/network/service.yaml, standard-app/templates/pdb.yaml, standard-app/templates/workloads/_container.tpl, standard-app/templates/workloads/cronjob.yaml, standard-app/templates/workloads/deployment.yaml, standard-app/templates/workloads/job.yaml
1. Abstracted `ConfigMap`, `ExternalSecret`, `Ingress`, `Service`, `labels` and `Container` into .tpl files and replaced with `include` statements with passed parameters
2. *Breaking change* Reworked ExternalSecrets' `dataFrom` entry: it now accepts a list of secret names to extract all secrets from
3. Fixed bugs with secrets mapping, env vars and secrets inheritance, resources and volumeMounts not being passed to cronjobs, secrets refresh interval in the values not being respected
4. Changed GHA trigger from `on.push` to `on.release.types[created]`
5. Set version to 1.0.0
`labels`, `env`, and `secrets` are currently merged in a top-down manner — from the root level (`.Values`), to the workload level (`job`, `cronjob`, or `deployment`), and finally to the `container` (or `initContainer`) …
=> Encapsulate common chart elements into templates

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/workloads/_spot_node_selection.tpl, standard-app/templates/workloads/cronjob.yaml, standard-app/templates/workloads/deployment.yaml, standard-app/templates/workloads/job.yaml
New functionality: set `.Values.preferSpot: aks` to include predefined `nodeAffinity` and toleration for AKS
In case another affinity of type `nodeAffinity` is set in the values.yaml - they are merged in a way that `nodeAffinity` key is not duplicated.
=> add spot nodes configuration for aks

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/workloads/deployment.yaml
Replaces hard coded default for `revisionHistoryLimit` with a configurable field but also a fallback to 2.
=> allow user to specify revision history limit for replicas

standard-app/Chart.yaml, standard-app/templates/configs/_externalsecret.tpl
adds a check for v1 of external-secrets and uses that if available, else use v1beta1.
Note, a future version will deprecate support for v1beta1
=> allow suppport for external-secrets.io/v1

standard-app/Chart.yaml, standard-app/templates/workloads/_container.tpl
Replace `merge` with `mergeOverwrite` which provides right-to-left precedence, ensuring container-level environment variables correctly override app-level variables, which override global variables.
Expected behavior: `Container > App > Global`
=> use mergeOverwrite for correct behavior when overwriting container envs

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/workloads/job.yaml
Adds a flag to allow jobs to use a provided name instead of generating one
=> allow jobs to use provided name

standard-app/Chart.yaml, standard-app/templates/configs/externalsecret.yaml
This PR:
- Made sure users can still use the external-secrets version `v1beta1` and `v1`
=> fix: Update External-Secrets API version v1/v1beta1

standard-app/Chart.yaml, standard-app/example.values.yaml, standard-app/templates/_labels.tpl, standard-app/templates/autoscaling/hpa.yaml, standard-app/templates/autoscaling/mpa.yaml, standard-app/templates/autoscaling/vpa.yaml, standard-app/templates/network/ingress.yaml, standard-app/templates/network/service.yaml, standard-app/templates/network/servicemonitor.yaml, standard-app/templates/pdb.yaml, standard-app/templates/workloads/cronjob.yaml, standard-app/templates/workloads/deployment.yaml, standard-app/templates/workloads/job.yaml
refactors the label template to allow resources to have app specific labels alongside global labels. 
earlier versions have a bug where:
- labels specific to apps are ignored
- using `merge` for labels in  `label.tpl` results in app/ingress specific labels are incorrectly applied across separate apps
side fixes: 
- correct default value for namespace selector for service monitor
- fix duplicate `secret.reloader.stakater.com/reload` annotations
=> fix: correct how labels are added to resources
